Repo,Error
j-v-n/Springboard,"HTTPSConnectionPool(host='api.github.com', port=443): Read timed out. (read timeout=15)"
Data-drone/DAIS2022-Scaling-Deep-Learning-Talk,"HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/Data-drone/DAIS2022-Scaling-Deep-Learning-Talk (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001BBC1373C40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
getindata/kedro-airflow-k8s,"HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/getindata/kedro-airflow-k8s (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001BBC1373F40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
Deena-Gergis/e2e_ds_project,"HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/Deena-Gergis/e2e_ds_project (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001BBC1373E50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
mlflow/mlp-regression-template,"HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/mlflow/mlp-regression-template (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001BBC1373BE0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
OmdenaAI/omdena-srilanka-tea-quality,"HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/OmdenaAI/omdena-srilanka-tea-quality (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001BBC1373EB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
altescy/xallennlp,"HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/altescy/xallennlp (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001BBC1373DC0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
mesosphere/dcos-docs-site,"HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/mesosphere/dcos-docs-site (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001BBC1373B80>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
averkij/a-studio,"HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/averkij/a-studio (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001BBC1373D90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
pnnl/deps_arXiv2020,"HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/pnnl/deps_arXiv2020 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001BBC1373D60>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
colbyford/sparkitecture,"HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/colbyford/sparkitecture (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001BBC1373E20>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
dmatrix/olt-mlflow,"HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/dmatrix/olt-mlflow (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001BBC1373E80>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
cogment/cogment-verse,"HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/cogment/cogment-verse (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001BBC1373C40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
AISaturdaysLagos/cohort7_practicals,"HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/AISaturdaysLagos/cohort7_practicals (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001BBC13728C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
HSG-AIML/RemoteSensingNO2Estimation,"HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/HSG-AIML/RemoteSensingNO2Estimation (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001BBC1373E50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
shibuiwilliam/mlflow_hydra_optuna_the_easy_way,"HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/shibuiwilliam/mlflow_hydra_optuna_the_easy_way (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001BBC1372140>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
li-phone/DefectNet,"HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/li-phone/DefectNet (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001BBC1373EB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
varunnair18/FISH,"HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/varunnair18/FISH (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001BBC1372230>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
mlflow/mlflow-export-import,"HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/mlflow/mlflow-export-import (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001BBC1373B80>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
Azure/fta-azure-machine-learning,"HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/Azure/fta-azure-machine-learning (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001BBC1372290>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
amazon-science/fact-graph,"HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/amazon-science/fact-graph (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001BBC1373D60>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
aws-samples/eks-kubeflow-workshop,"HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/aws-samples/eks-kubeflow-workshop (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001BBC13722F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
nnaisense/evotorch,"HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/nnaisense/evotorch (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001BBC1373E80>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
eto-ai/etosdk,"HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/eto-ai/etosdk (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001BBC1372350>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
vfdev-5/UDA-pytorch,"HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/vfdev-5/UDA-pytorch (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001BBC13728C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
microsoft/LoRA,"HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/microsoft/LoRA (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001BBC13723B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
bentoml/benchmark,"HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/bentoml/benchmark (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001BBC1372140>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
microsoft/DeepSpeedExamples,"HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/microsoft/DeepSpeedExamples (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001BBC1372410>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
A3Data/hermione,"HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/A3Data/hermione (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001BBC1372230>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
MindRank-Biotech/PharmKG,"HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/MindRank-Biotech/PharmKG (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001BBC1372470>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
sofianhamiti/amazon-sagemaker-pipelines-mlflow,"HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/sofianhamiti/amazon-sagemaker-pipelines-mlflow (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001BBC1372290>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
ThinamXx/MLOps,"HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/ThinamXx/MLOps (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001BBC13724D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
marcusRB/The_Bridge_DataScience_PT_ALUMNI_feb22,"404 {""message"": ""Not Found"", ""documentation_url"": ""https://docs.github.com/rest/reference/repos#get-a-repository""}"
